language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_dev.txt

# TODO: Test the deployment
script: tox

# Generate PYPI package on tagged versions on master
deploy.sh:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/mantaray
    python: 3.6
